### ISSUE TITLE
Tooltip added to "Plugin Manager" menubar button

### ISSUE THREAD

**Issue by XertroV** [GreepTheSheep/openplanet-replay-recorder#3]
Yeah, sounds weird, ey.

![image](https://user-images.githubusercontent.com/1046448/170961659-0f8f5f20-729a-45e0-96cd-1e60b0de2133.png)

I think it's due to this line interacting with `UI::IsItemHovered()`: https://github.com/GreepTheSheep/openplanet-replay-recorder/blob/97cfe49b34d8f9868935560e5e73e12386312000/src/Main.as#L31

Moving the entire `RenderMenuMain` function body inside a `if(g_replayRecord.m_inProgress){ ... }` will probably fix the issue.

**Comment by GreepTheSheep** [comment]
Yeah I'm already aware of that. Miss (Openplanet dev) says that's a internal Openplanet bug (not a plugin bug) so I think it can be fixed on the next (edge/beta maybe) release of Openplanet.

I can add a workaround by adding a condition `m_inProgress` on `IsItemHovered()` too, but i'll prefer wait for an update on Openplanet side to see if it's fixed

**Comment by XertroV** [comment]
> Miss (Openplanet dev) says that's a internal Openplanet bug (not a plugin bug) so I think it can be fixed on the next (edge/beta maybe) release of Openplanet.

IDK about that -- like there might be a related bug in openplanet, but I think there's also a bug here.

WRT openplanet: it seems reasonable that it is a bug if one plugin can change the UI of another plugin. But that wasn't your intention.

Currently, the logic is like this (in python / pseudocode):

```python
if inProgress:
  if uiMenuItem():
    inProgress = false
if uiIsItemHovered():
  drawUiStuff()
```

the bug is that `uiMenuItem()` is only called when `inProgress` is `true`, but `uiIsItemHovered()` is called regardless of whether `inProgress` is true.

`uiIsItemHovered()` has some implicit state about the last UI element that was drawn, but only when `inProgress == true` is the last element the *intended* element: the menu item.

rather, the call to `uiIsItemHovered()` should only be called in the context that `uiMenuItem` is called, which is conditional on `inProgress`.

so the corrected logic -- in python -- is just changing the indentation:

```python
if inProgress:
  if uiMenuItem():
    inProgress = false
  if uiIsItemHovered():
    drawUiStuff()
```

> I can add a workaround by adding a condition m_inProgress on IsItemHovered() too

So I don't think that's a workaround, it's just the solution (thought other groupings might be preferable depending on taste).
